=== Steps to publish a dataset in GBIF

Anyone interested in publishing a dataset in GBIF can do so by registering an organization - GBIF only publishes datasets from individuals affiliated to an organization. Please check the page on how to https://www.gbif.org/become-a-publisher[become a publisher^] and the https://www.gbif.org/publishing-data[quick guide to publishing data through GBIF^].

The next step is to prepare the data into files that will be published as Darwin Core Archives (see https://www.gbif.org/standards[data standards^]), prior to publication is important to perform a data cleaning step and prepare the metadata, once the data is uploaded in an IPT, the data holder must select one of the three licences used by GBIF and then, the dataset can be published and registered as a resource in GBIF. Figure 1 summarizes the basic steps to data publication in GBIF.

[[fig-01]]
.A simplified flow for data publishing in GBIF. Steps will be referred to in the text below with a link to the appropriate sections in this guide.

==== Choose a dataset class

There are four https://www.gbif.org/dataset-classes[dataset classes^] that are supported for publication in GBIF: metadata-only datasets, checklist, occurrence, and sampling-event datasets. For more information, please check https://data-blog.gbif.org/post/choose-dataset-type[how to choose a dataset class on GBIF^]

For more details on data categorization, please check data-categorization[section 2^] of this guide.


==== Data cleaning and mapping the data to the DwC standard

