== Quick links to resources

Here we provide a list of useful or relevant links to websites and resources to facilitate data publishing in GBIF. For convenience, links are organized by category.

=== General information and guides

I’m still trying to figure out what to with chapter 3, my intention is to provide an easy to find list of useful links. As a publisher myself I often needed help to sort out the data, like how can I convert coordinates or parse names, where to find controlled vocabulary definitions…and having a list like would have save me some time, and that’s why I’ve been compiling this list – in a messier way - over the years.

///
* {blank}
+
____
https://dwc.tdwg.org/terms/[[.underline]#Darwin Core term Quick
Reference Guide#]
____
* {blank}
+
____
https://dwc.tdwg.org/text/[[.underline]#Darwin Core text guide#]
____
* {blank}
+
____
https://techdocs.gbif.org/en/[[.underline]#GBIF Technical Documents#]
____
* {blank}
+
____
GBIF https://www.gbif.org/dataset-classes[[.underline]#dataset classes#]
____
* {blank}
+
____
GBIF
https://ipt.gbif.org/manual/en/ipt/latest/resource-metadata[[.underline]#resource
metadata#]
____
* {blank}
+
____
https://docs.gbif.org/publishing-dna-derived-data/en/[[.underline]#Publishing
DNA-derived data guide#]
____
* {blank}
+
____
Best
https://ipt.gbif.org/manual/en/ipt/latest/best-practices-sampling-event-data[[.underline]#practices#]
for publishing sampling event datasets
____
* {blank}
+
____
Introduction to
https://www.gbif.org/sampling-event-data[[.underline]#event#] data
____
* {blank}
+
____
How to
https://ipt.gbif.org/manual/en/ipt/latest/how-to-publish[[.underline]#publish#]
datasets
____
* {blank}
+
____
Consortium E, Body G, de Mousset M, Chevallier E, Scandura M, Pamerlon
S, et al. Applying the Darwin core standard to the monitoring of
wildlife species, their management and estimated records. EFSA
Supporting Publications. 2020;17(4):1841E.
https://onlinelibrary.wiley.com/doi/abs/10.2903/sp.efsa.2020.EN-1841[[.underline]#https://onlinelibrary.wiley.com/doi/abs/10.2903/sp.efsa.2020.EN-1841#]
____
* {blank}
+
____
Consortium E, Jaroszynska F, Body G, Pamerlon S, Archambeau AS. Applying
the Darwin Core data standard to wildlife disease – advancements toward
a new data model. EFSA Supporting Publications. 2022;19(11):7667E.
____

____
https://onlinelibrary.wiley.com/doi/abs/10.2903/sp.efsa.2022.EN-7667[[.underline]#https://onlinelibrary.wiley.com/doi/abs/10.2903/sp.efsa.2022.EN-7667#]
____

* {blank}
+
____
Groom Q, Desmet P, Reyserhove L, Adriaens T, Oldoni D, Vanderhoeven S,
et al. Improving Darwin Core for research and management of alien
species. Biodiversity Information Science and Standards. 2019 Oct
10;3:e38084.https://biss.pensoft.net/article/38084/[[.underline]#https://biss.pensoft.net/article/38084/#]
____

=== 3.2. Coordinates, mapping and Georeferencing

* {blank}
+
____
http://data.canadensys.net/tools/coordinates[[.underline]#Coordinate
Conversion Tool#]: used to convert coordinates from degrees minutes
seconds to decimal degrees
____
* {blank}
+
____
http://splink.cria.org.br/infoxy?criaLANG=en[[.underline]#InfoXY#] from
CRIA for validating geographic data
____
* {blank}
+
____
http://georeferencing.org/georefcalculator/gc.html[[.underline]#Georeferencing
Calculator#], a point-radius method for georeferencing locality
descriptions and calculating associated uncertainty
____
* {blank}
+
____
Bloom DA, Wieczorek JR & Zermoglio PF (2020) Georeferencing Calculator
Manual. Copenhagen: GBIF Secretariat.
https://doi.org/10.35035/gdwq-3v93[[.underline]#https://doi.org/10.35035/gdwq-3v93#]
____
* {blank}
+
____
Chapman AD & Wieczorek JR (2020) Georeferencing Best Practices.
Copenhagen: GBIF Secretariat.
https://doi.org/10.15468/doc-gg7h-s853[[.underline]#https://doi.org/10.15468/doc-gg7h-s853#]
____
* {blank}
+
____
Zermoglio PF, Chapman AD, Wieczorek JR, Luna MC & Bloom DA (2020)
Georeferencing Quick Reference Guide. Copenhagen: GBIF Secretariat.
https://doi.org/10.35035/e09p-h128[[.underline]#https://doi.org/10.35035/e09p-h128#]
____
* {blank}
+
____
https://www.getty.edu/research/tools/vocabularies/tgn/[[.underline]#Getty
Thesaurus of Geographic Names#]: search interface for place names
____

=== 3.3. Controlled vocabulary & ontologies

* {blank}
+
____
https://rs.gbif.org/vocabulary/dwc/basis_of_record_2022-02-02.xml[[.underline]#Darwin
Core Basis of Record Vocabulary#]: definitions for terms used to
populate basisOfRecord
____
* {blank}
+
____
Metadata descriptors for health:
https://decs.bvsalud.org/en/[[.underline]#DeCS/MeSH#],
https://www.globalindexmedicus.net/[[.underline]#Global Index Medicus#],
https://www.nlm.nih.gov/research/umls/index.html[[.underline]#Unified
Medical Language System (UMLS)#]
____
* {blank}
+
____
Repository for biomedical ontologies:
https://www.ebi.ac.uk/ols4/[[.underline]#EMBL-EBI Ontology Lookup
Service#] , for ontologies on habitat, e.g.
https://www.ebi.ac.uk/ols4/ontologies/envo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FENVO_03501257[[.underline]#barn#];
gonotrophic cycle, e.g.
https://www.ebi.ac.uk/ols4/ontologies/idomal/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FIDOMAL_0001044[[.underline]#exophily#];
detection assays, e.g.
https://ontobee.org/ontology/NCIT?iri=http://purl.obolibrary.org/obo/NCIT_C16553[[.underline]#ELISA#];
among others.
____
* {blank}
+
____
For more general health information, the
https://www.healthit.gov/topic/standards-technology/standards/fhir[[.underline]#HL7®
FHIR®#] is an interoperability standard designed to enable health data
sharing.
____

=== 3.4. Taxonomy & Date issues

* {blank}
+
____
https://www.gbif.org/tools/name-parser[[.underline]#GBIF Name parser#]:
tool to divide scientific names into their components and to check them
against the taxonomic backbone used by GBIF
____
* {blank}
+
____
GBIF's https://www.gbif.org/tools/species-lookup[[.underline]#species
lookup#]: to normalize species names against the GBIF backbone
____
* {blank}
+
____
https://www.checklistbank.org/[[.underline]#ChecklistBank#]
____
* {blank}
+
____
https://data.canadensys.net/tools/dates#:~:text=Use%20this%20tool%20to%20parse,a%20tab%20or%20a%20pipe.[[.underline]#Canadensys
Date parser#]: tool to parse dates into component parts
____
* {blank}
+
____
A
https://discourse.gbif.org/t/a-guide-to-date-issues/4185[[.underline]#guide#]
to date issues
____
* {blank}
+
____
https://discourse.gbif.org/t/how-to-handle-the-event-dwc-fields-for-trap-base-occurrence/3162/4[[.underline]#How
to#] handle date intervals
____

=== 3.5. Quality control tools & resources

* {blank}
+
____
Data quality
https://ipt.gbif.org/manual/en/ipt/latest/data-quality-checklist[[.underline]#checklist#]
____
* {blank}
+
____
GBIF's https://www.gbif.org/tools/data-validator[[.underline]#data
validator#]
____
* {blank}
+
____
Zermoglio PF, Plata Corredor CA, Wieczorek JR, Ortiz Gallego R &
Buitrago L (2021) Guía para la limpieza de datos sobre biodiversidad con
OpenRefine. Versión 3. Copenhagen: GBIF Secretariat.
https://doi.org/10.15468/doc-gzjg-af18[[.underline]#https://doi.org/10.15468/doc-gzjg-af18#]
____
* {blank}
+
____
https://openrefine.org/[[.underline]#OpenRefine#] free, open source tool
for cleaning data.
____
* {blank}
+
____
https://hbiostat.org/r/hmisc/[[.underline]#Hmisc R package#] for
summarizing data, useful for checking data quality and outliers
____
* {blank}
+
____
https://bionomia.net/[[.underline]#Bionomia#], is an online platform
that links people to specimens specimens
(https://pmc.ncbi.nlm.nih.gov/articles/PMC9836581/#B8055638[[.underline]#Shorthouse
2020#]), and allows for name disambiguation when one collector has used
different names, or a name is written in more than one way. The specimen
data associated with the terms
http://rs.tdwg.org/dwc/terms/recordedBy[[.underline]#recordedBy#],
http://rs.tdwg.org/dwc/terms/recordedByID[[.underline]#recordedByID#],
http://rs.tdwg.org/dwc/terms/identifiedBy[[.underline]#identifiedBy#],
http://rs.tdwg.org/dwc/terms/identifiedByID[[.underline]#identifiedByID#]
are used by Bionomia to generate attribution.
____

* {blank}
+
____
https://zenodo.org/record/6453921#.Y9KsQkHMKmU[[.underline]#Excel to
Darwin Core Standard (DwC) Tool#]: creates templates for Event,
Occurrence, MeasurementsOrFacts, Extended MeasurementsOrFacts (EMoF),
and Simple Multimedia tables.
____
* {blank}
+
____
https://sios-svalbard.org/aen/template-generator/[[.underline]#Darwin
Core Template Generator for Event and Occurrence tables#]: user can
choose DwC terms to generate template for Event and Occurrence tables,
developed by the Nansen Legacy project.
____
* {blank}
+
____
Template
https://gbif-norway.github.io/dwc-excel-template-generator-js[[.underline]#generator#]
by GBIF Norway
____
* {blank}
+
____
Table converter from columns to rows
https://mycena.sibbr.gov.br/[[.underline]#https://mycena.sibbr.gov.br/#]
by GBIF Brazil - SiBBr (in Portuguese).
____

=== 3.7. Publishing Tools & Links

* {blank}
+
____
https://ipt.gbif.org/manual/en/ipt/latest/[[.underline]#Integrated
Publishing Toolkit (IPT) User Manual#]
____
* {blank}
+
____
https://eml.ecoinformatics.org/[[.underline]#Ecological Metadata
Language (EML) guide#]
____
* {blank}
+
____
https://www.gbif.org/become-a-publisher[[.underline]#Become a GBIF
publisher#]: necessary for dataset publication in GBIF
///