== Future prospects

As VBDs continue to affect endemic countries or emerge and re-emerge throughout different regions of the world, continued efforts to provide open and accessible data about the biodiversity of these systems is crucial to developing effective prevention, control and elimination strategies. The value of data sharing has been evident during multiple public health emergencies of international concern (PHEICs), including the 2003 SARS outbreak, the Zika epidemic in 2015, and the COVID-19 pandemic, resulting in multiple manuscripts and frameworks published (https://iris.who.int/handle/10665/352859[WHO 2022^]). One way to improve data sharing is to focus on efforts in long term endemic systems, as well as during inter-epidemic periods by facilitating learning and consolidating data sharing practices, which will strengthen concerted, focused public health actions against endemic and epidemic prone VBDs. With this guide, we hope to provide a set of practical recommendations to help publish open vector data in the GBIF.org portal to contribute to the understanding of vector distributions and disease dynamics.

Currently, searching for GBIF extensions is possible by using the GBIF API which enables users to make advanced queries that are not supported by the website. Please check the https://techdocs.gbif.org/en/openapi[API reference^] and the https://data-blog.gbif.org/post/gbif-api-beginners-guide[API beginners guide^]. The ResourceRelationship extension remains the best choice for handling interaction data without some degree of data loss, and GBIF and the Darwin Core Maintenance Group are working towards developing a new data model that will encompass the range and complexity of additional data types (https://www.gbif.org/new-data-model[Wieczorek & Robertson 2023]). Overall, sharing data on vectors in GBIF will contribute to better preparedness, prevention and control of VBDs to improve human population health.
