== Acknowledgements

The guide has been prepared in the context of collaboration in the https://www.vectoratlas.icipe.org/about[Vector Atlas project^] (collaboration agreement ATR04590 between the University of Oxford, UK and the GBIF Secretariat).

We would like to thank https://orcid.org/0000-0003-1186-2688[Olivier Briet^] for valuable discussion on mapping terms and developing the Resource Relationship extension for vector data and https://orcid.org/0009-0002-2689-6434[Clara Baringo^] for discussion on the Darwin core standard. We are grateful to Victoire Nsabatien[Victoire Nsabatien^] and https://orcid.org/0000-0002-0927-9365[Catalina Marcelo Diaz^] for revising the draft version of this guide. We thank https://orcid.org/0000-0002-7362-5621[Theeraphap Chareonviriyaphap^], https://orcid.org/0000-0002-5925-7164[Sylvie Manguin^] and https://orcid.org/0000-0001-7145-3179[Marianne Sinka^] for their support as members of the GBIF Task-group on mobilization and use of biodiversity data for research and policy on human diseases. And we are also grateful to https://orcid.org/0000-0003-3918-4065[Andrea Hahn^] and https://orcid.org/0000-0002-6590-599X[Kyle Copas^] for support and valuable discussions on the GBIF data publishing infrastructure.
