== Acknowledgements

The guide has been prepared in the context of collaboration in the https://www.vectoratlas.icipe.org/about[Vector Atlas project^] (collaboration agreement ATR04590 between the University of Oxford, UK and the GBIF Secretariat).

We would like to thank https://orcid.org/0000-0003-1186-2688[Olivier Brietˆ] for valuable discussion on mapping terms and developing the Resource Relationship extension for vector data and https://orcid.org/0009-0002-2689-6434[Clara Baringoˆ] for discussion on the Darwin core standard. We are grateful to Victoire Nsabatien[Victoire Nsabatienˆ] and https://orcid.org/0000-0002-0927-9365[Catalina Marcelo Diazˆ] for revising the draft version of this guide. We thank https://orcid.org/0000-0002-7362-5621[Theeraphap Chareonviriyaphapˆ], https://orcid.org/0000-0002-5925-7164[Sylvie Manguinˆ] and https://orcid.org/0000-0001-7145-3179[Marianne Sinkaˆ] for their support as members of the GBIF Task-group on mobilization and use of biodiversity data for research and policy on human diseases. And we are also grateful to https://orcid.org/0000-0003-3918-4065[Andrea Hahnˆ] and https://orcid.org/0000-0002-6590-599X[Kyle Copasˆ] for support and valuable discussions on the GBIF data publishing infrastructure.
