== Acknowledgements

The guide has been prepared in the context of collaboration in the https://www.vectoratlas.icipe.org/about[Vector Atlas project^] (collaboration agreement ATR04590 between the University of Oxford, UK and the GBIF Secretariat).

This guide is based on the work and discussions of the https://assets.ctfassets.net/uo17ejk9rkwj/3qrvu3fyrXdRAmkFvHgLNo/4703e960997e81664cc399d14801a249/human-disease-task-group-TOR_2.pdf[task group^] on mobilization and use of biodiversity data for research and policy on human diseases that was active between 2020-2025. 

We would like to thank the https://tdr.who.int/[Special Programme for Research and Training in Tropical Diseases(TDR/WHO)^] and https://orcid.org/0000-0001-6444-1436[Scott Edmunds^] from Gigabyte Journal https://gigabytejournal.com/articles/series/GIGABYTE_SERIES_0002[special issue^] and https://doi.org/10.1093/gigascience/giac114[paper^] for sponsoring and supporting, respectively, the series on data papers describing datasets on vectors of human diseases.

Special thanks to https://orcid.org/0000-0003-1186-2688[Olivier Briet^] for valuable discussion on mapping terms and developing the Resource Relationship extension for vector data. We are thankful to https://orcid.org/0000-0002-2946-3020[Sofie Dhollander^] and https://orcid.org/0000-0001-9333-1340[Cedric Marsboom^] for their support to open vector data. We are also grateful to https://orcid.org/0009-0002-2689-6434[Clara Baringo^] for discussion on the Darwin core standard, and to https://orcid.org/0000-0002-0750-6106[Victoire Nsabatien^] and https://orcid.org/0000-0002-0927-9365[Catalina Marcelo Diaz^] for revising the draft version of this guide. We acknowledge https://orcid.org/0000-0002-7362-5621[Theeraphap Chareonviriyaphap^], https://orcid.org/0000-0002-5925-7164[Sylvie Manguin^] and https://orcid.org/0000-0001-7145-3179[Marianne Sinka^] for their support as members of the GBIF Task-group on mobilization and use of biodiversity data for research and policy on human diseases. And we are also very grateful to https://orcid.org/0000-0003-3918-4065[Andrea Hahn^] and https://orcid.org/0000-0002-6590-599X[Kyle Copas^] for support and valuable discussions on the GBIF data publishing infrastructure.



